#%RAML 1.0
title: Fact Benchmark API
version: 0.5
baseUri: http://factapi.org
baseUriParameters: {}
protocols:
- HTTP
documentation:
- title: Fact Benchmark API
  content: "This API aims to provide an independent, realtime, collective shared resource by which researchers working in the field can collaborate to push the state of the art in timely factcheck detection."
types:
  ContentHash:
    example:
      value:
        hash: ''
        data: ''
        mime: ''
    displayName: ContentHash
    type: object
    properties:
      hash:
        required: false
        displayName: hash
        type: string
      data:
        required: false
        displayName: data
        type: string
      mime:
        required: false
        displayName: mime
        description: type (string)
        type: string
  DeclineToRate:
    displayName: DeclineToRate
    type: object
    properties:
      reason:
        required: false
        displayName: reason
        type: string
        enum:
        - not falsifiable
        - not falsifiable - better option exists
        - not a good summation
        - not a good summation - better option exists
      preferred_alternative:
        required: false
        displayName: preferred_alternative
        type: string
  ClaimBase:
    displayName: ClaimBase
    type: object
    properties:
      claim_text:
        required: false
        displayName: claim_text
        type: string
      source:
        required: false
        displayName: source
        type: string
      attribution:
        required: false
        displayName: attribution
        type: string
      timestamp:
        required: false
        displayName: timestamp
        type: string
      raw:
        required: false
        displayName: raw
        type: ContentHash
      submitted_by:
        required: false
        displayName: submitted_by
        type: string
      hidden_date:
        required: false
        displayName: hidden_date
        type: string
  RumorBase:
    displayName: RumorBase
    type: object
    properties:
      id:
        required: false
        displayName: id
        type: string
      created:
        required: false
        displayName: created
        type: string
      label:
        required: false
        displayName: label
        description: Preferred label of rumor (for use in UI)
        type: string
      related_claims:
        required: false
        displayName: related_claims
        description: claims associated with this rumor
        type: array
        items:
          type: string
      preferred_claim:
        required: false
        displayName: preferred_claim
        type: string
  CallBase:
    displayName: CallBase
    type: object
    properties:
      call:
        required: false
        displayName: call
        description: True/false value
        type: boolean
      weighting:
        required: false
        displayName: weighting
        description: Amount true (call must be true if this weighting is non null)
        type: number
        format: double
      timestamp:
        required: false
        displayName: timestamp
        type: string
      submitted_by:
        required: false
        displayName: submitted_by
        type: string
      data:
        required: false
        displayName: data
        type: ContentHash
      decline:
        required: false
        displayName: decline
        type: DeclineToRate
  PostBase:
    example:
      value:
        label: "'Posting this message on your facebook will earn you money'"
        source: ''
        attribution: ''
        timestamp: 2018-09-04T04:29:00.0000000Z
        raw:
          hash: ''
          data: ''
          mime: ''
        submitted_by: ''
        hidden_date: ''
    displayName: PostBase
    type: object
    properties:
      label:
        required: false
        displayName: label
        description: created by submitter to summarize post, but not normative
        type: string
      source:
        required: false
        displayName: source
        type: string
      attribution:
        required: false
        displayName: attribution
        type: string
      timestamp:
        required: false
        displayName: timestamp
        type: string
      raw:
        required: false
        displayName: raw
        type: ContentHash
      submitted_by:
        required: false
        displayName: submitted_by
        type: string
      hidden_date:
        required: false
        displayName: hidden_date
        type: string
  Claim:
    example:
      value:
        claim_text: "'Student arrested for shouting slogans against BJP in Tamil Nadu'"
        source: https://twitter.com/anindita_guha/status/1036924232595382273
        attribution: https://twitter.com/LKC1965
        timestamp: 2018-09-04T04:29:00.0000000Z
        raw:
          hash: ''
          data: ''
          mime: ''
        submitted_by: faktist216
        hidden_date: ''
        id: 08ff7052-2e95-11e3-a1fc-000c294eede0
        created: 2019-01-01T01:23:00.0000000Z
    displayName: Claim
    type: ClaimBase
    properties:
      id:
        required: false
        displayName: id
        type: string
      created:
        required: false
        displayName: created
        type: string
  request:
    example:
      value:
        claim_text: "'Student arrested for shouting slogans against BJP in Tamil Nadu'"
        source: https://twitter.com/anindita_guha/status/1036924232595382273
        attribution: https://twitter.com/LKC1965
    displayName: request
    type: object
    properties:
      claim_text:
        required: false
        displayName: claim_text
        type: string
      source:
        required: false
        displayName: source
        type: string
      attribution:
        required: false
        displayName: attribution
        type: string
/claims:
  get:
    displayName: ListallClaims
    description: Subscribe to a websocket to receive notification of claims as they are published.
    queryParameters:
      last_seen:
        required: false
        displayName: last_seen
        description: The timestamp of the last claim received by client (only send claims after this).
        type: string
    responses:
      200:
        description: Success
        headers:
          Content-Type:
            default: application/json
            displayName: Content-Type
            type: string
        body:
          application/json:
            example:
              value:
              - claim_text: "'Student arrested for shouting slogans against BJP in Tamil Nadu'"
                source: https://twitter.com/anindita_guha/status/1036924232595382273
                attribution: https://twitter.com/LKC1965
                timestamp: 2018-09-04T04:29:00.0000000Z
                raw:
                  hash: ''
                  data: ''
                  mime: ''
                submitted_by: faktist216
                hidden_date: ''
                id: 08ff7052-2e95-11e3-a1fc-000c294eede0
                created: 2019-01-01T01:23:00.0000000Z
            displayName: response
            type: array
            items:
              type: Claim
  /{id}:
    uriParameters:
      id:
        required: true
        displayName: id
        description: The ID of the desired claim.
        type: string
    post:
      displayName: SubmitaClaim
      description: "A claim is any statement with an attribution.\nTo be interesting for analysis a claim should be \nfalsifiable and of general interest.\n**Update Model**: idempotentSubmit a claim for consideration in the benchmark."
      body:
        application/json:
          example:
            value:
              claim_text: "'Student arrested for shouting slogans against BJP in Tamil Nadu'"
              source: https://twitter.com/anindita_guha/status/1036924232595382273
              attribution: https://twitter.com/LKC1965
          displayName: body
          type: request
      headers:
        Content-Type:
          required: true
          example:
            value: application/json
          displayName: Content-Type
          type: string
      responses:
        200:
          description: Success
          headers:
            Content-Type:
              default: application/json
              displayName: Content-Type
              type: string
          body:
            application/json:
              example:
                value:
                  claim_text: "'Student arrested for shouting slogans against BJP in Tamil Nadu'"
                  source: https://twitter.com/anindita_guha/status/1036924232595382273
                  attribution: https://twitter.com/LKC1965
                  timestamp: 2018-09-04T04:29:00.0000000Z
                  raw:
                    hash: ''
                    data: ''
                    mime: ''
                  submitted_by: faktist216
                  hidden_date: ''
                  id: 08ff7052-2e95-11e3-a1fc-000c294eede0
                  created: 2019-01-01T01:23:00.0000000Z
              displayName: response
              type: Claim
    get:
      displayName: RetrieveaClaim
      description: "A claim is any statement with an attribution.\nTo be interesting for analysis a claim should be \nfalsifiable and of general interest.\n**Update Model**: idempotentRetrieves the claim with the given ID."
      responses:
        200:
          description: Success
          headers:
            Content-Type:
              default: application/json
              displayName: Content-Type
              type: string
          body:
            application/json:
              example:
                value:
                  claim_text: "'Student arrested for shouting slogans against BJP in Tamil Nadu'"
                  source: https://twitter.com/anindita_guha/status/1036924232595382273
                  attribution: https://twitter.com/LKC1965
                  timestamp: 2018-09-04T04:29:00.0000000Z
                  raw:
                    hash: ''
                    data: ''
                    mime: ''
                  submitted_by: faktist216
                  hidden_date: ''
                  id: 08ff7052-2e95-11e3-a1fc-000c294eede0
                  created: 2019-01-01T01:23:00.0000000Z
              displayName: response
              type: Claim
/rumors:
  get:
    displayName: ListallRumors
    description: Subscribe to a websocket to receive notification of Rumors as they are approved for the benchmark.
    queryParameters:
      last_seen:
        required: false
        displayName: last_seen
        description: The timestamp of the last Rumor received by client (only send Rumors after this).
        type: string
    responses:
      200:
        description: Success
        headers:
          Content-Type:
            default: application/json
            displayName: Content-Type
            type: string
        body:
          application/json:
            displayName: response
            type: array
            items:
              type: RumorBase
  /{id}:
    uriParameters:
      id:
        required: true
        displayName: id
        description: The ID of the desired Rumor.
        type: string
    get:
      displayName: RetrieveaRumor
      description: |
        Claims (and articles) are sometimes grouped together as relating to the same 'rumour'.

        A claim must be attached to a rumor to be entered into the benchmark.

        Claims can be submitted and calls made at any time, but they are not considered part of the benchmark until they are approved.

        **Update Model**: CDRT logRetrieves the Rumor with the given ID.
      responses:
        200:
          description: Success
          headers:
            Content-Type:
              default: application/json
              displayName: Content-Type
              type: string
          body:
            application/json:
              displayName: response
              type: RumorBase
/calls:
  get:
    displayName: ListallCalls
    description: Subscribe to a websocket to receive notification of calls as they are received, and/or relating to a specific rumor.
    queryParameters:
      last_seen:
        required: false
        displayName: last_seen
        description: The timestamp of the last call received by client (only send Calls after this).
        type: string
      regarding:
        required: false
        displayName: regarding
        type: string
    responses:
      200:
        description: Success
        headers:
          Content-Type:
            default: application/json
            displayName: Content-Type
            type: string
        body:
          application/json:
            displayName: response
            type: array
            items:
              type: CallBase
  /{id}:
    uriParameters:
      id:
        required: true
        displayName: id
        description: The ID of the  call to retrive.
        type: string
    get:
      displayName: Retrieveacall
      description: |
        A call is an evaluation as to the veracity of a statement.

        This is the primary method by which reputation points are earned in the benchmark.

       
        **Update Model**: IdempotentRetrieves the call with the given ID.
      responses:
        200:
          description: Success
          headers:
            Content-Type:
              default: application/json
              displayName: Content-Type
              type: string
          body:
            application/json:
              displayName: response
              type: CallBase
/post/{id}:
  uriParameters:
    id:
      required: true
      displayName: id
      description: The ID of the post to retrive.
      type: string
  get:
    displayName: RetrievePost
    description: "A post is a longer statement with or without attribution.\nTo be interesting for analysis a post should be \nfalsifiable and of general interest (in the same way\nas described for claims).\nA post is a more general form of a claim.Retrieves content with the given id"
    responses:
      200:
        description: Success
        headers:
          Content-Type:
            default: application/json
            displayName: Content-Type
            type: string
        body:
          application/json:
            example:
              value:
                label: "'Posting this message on your facebook will earn you money'"
                source: ''
                attribution: ''
                timestamp: 2018-09-04T04:29:00.0000000Z
                raw:
                  hash: ''
                  data: ''
                  mime: ''
                submitted_by: ''
                hidden_date: ''
            displayName: response
            type: PostBase
/user/{hash}:
  uriParameters:
    hash:schema
      required: false
      displayName: hash
      type: string
  get:
    displayName: Retrievecontent
    description: Retrieves content with the given ContentHash
    responses:
      200:
        description: Success
        headers:
          Content-Type:
            default: application/json
            displayName: Content-Type
            type: string
        body:
          application/json:
            example:
              value:
                hash: ''
                data: ''
                mime: ''
            displayName: response
            type: ContentHash