#%RAML 1.0
title: Fact Benchmark API
baseUri: http://factapi.org/{version}
version: v0.5
baseUriParameters: {}
protocols:
- HTTP
documentation:
- title: Fact Benchmark API
  content: "This API aims to provide an independent, realtime, collective shared resource by which researchers in the field can collaborate"
/statements:
  get:
  post:
  /{id}:
    get:
    /annotatoins:
      get:
    /responses:
      get:
/responses:
  get:
  post:
/annotations:
  get:
  post:
/benchmarks:
  get:
  post:
  /{id}:
    get:
/content:
  post:
  /{hash}:
    get:
